# Generated by Django 5.0.7 on 2024-07-15 09:52

import django.db.models.deletion
import localflavor.in_.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_1", models.CharField(max_length=120)),
                ("address_2", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(max_length=50)),
                (
                    "state",
                    localflavor.in_.models.INStateField(default="MH", max_length=2),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.location",
            ),
        ),
    ]
