# Generated by Django 5.0.7 on 2024-07-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_location_profile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="zip_code",
            field=models.IntegerField(default=400001),
        ),
    ]
