# Generated by Django 5.0.7 on 2024-07-16 09:18

import users.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(null=True, upload_to=users.util.user_upload_dir),
        ),
    ]
