# Generated by Django 5.0.7 on 2024-07-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_likedlisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
